"""make household_type and diet_type nullable

Revision ID: d728c68a8d3a
Revises: 0001
Create Date: 2026-07-01 17:11:18.183044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd728c68a8d3a'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_members', 'health_flags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'preferred_order_day',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'preferred_order_time',
               existing_type=postgresql.TIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_staples',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_fresh_produce',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_dairy_eggs',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_packaged',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'preferred_delivery_slot',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('household_preferences', 'confirmation_window_hrs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('fk_prefs_preferred_address', 'household_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'household_preferences', 'addresses', ['preferred_address_id'], ['id'])
    op.alter_column('households', 'whatsapp_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('households', 'whatsapp_opted_out',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('households', 'household_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('households', 'member_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('households', 'diet_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('households', 'allergies',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('households', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('households', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('households', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('households', 'city',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loop_run_items', 'is_substitution',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loop_run_items', 'was_in_stock',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loop_runs', 'trigger_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loop_runs', 'state',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loop_runs', 'substitutions_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loop_runs', 'items_unavailable',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'taxes',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'pantry_updated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('fk_orders_loop_run', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'loop_runs', ['loop_run_id'], ['id'])
    op.alter_column('pantry_items', 'estimated_qty_remaining',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pantry_items', 'consumption_confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pantry_items', 'times_ordered',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pantry_items', 'times_removed_by_user',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pantry_items', 'times_kept_by_user',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pantry_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('swiggy_tokens', 'nudge_48hr_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('swiggy_tokens', 'nudge_24hr_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('swiggy_tokens', 'nudge_expired_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swiggy_tokens', 'nudge_expired_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('swiggy_tokens', 'nudge_24hr_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('swiggy_tokens', 'nudge_48hr_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('pantry_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('pantry_items', 'times_kept_by_user',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pantry_items', 'times_removed_by_user',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pantry_items', 'times_ordered',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pantry_items', 'consumption_confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('pantry_items', 'estimated_qty_remaining',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_loop_run', 'orders', 'loop_runs', ['loop_run_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'pantry_updated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'placed'::character varying"),
               existing_nullable=False)
    op.alter_column('orders', 'taxes',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('loop_runs', 'items_unavailable',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('loop_runs', 'substitutions_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('loop_runs', 'state',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('loop_runs', 'trigger_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'scheduled'::character varying"),
               existing_nullable=False)
    op.alter_column('loop_run_items', 'was_in_stock',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('loop_run_items', 'is_substitution',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('households', 'city',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Bengaluru'::character varying"),
               existing_nullable=False)
    op.alter_column('households', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('households', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('households', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('households', 'allergies',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('households', 'diet_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('households', 'member_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('households', 'household_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('households', 'whatsapp_opted_out',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('households', 'whatsapp_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'household_preferences', type_='foreignkey')
    op.create_foreign_key('fk_prefs_preferred_address', 'household_preferences', 'addresses', ['preferred_address_id'], ['id'], ondelete='SET NULL')
    op.alter_column('household_preferences', 'confirmation_window_hrs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('4'),
               existing_nullable=False)
    op.alter_column('household_preferences', 'preferred_delivery_slot',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'evening'::character varying"),
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_packaged',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'weekly'::character varying"),
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_dairy_eggs',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'weekly'::character varying"),
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_fresh_produce',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'weekly'::character varying"),
               existing_nullable=False)
    op.alter_column('household_preferences', 'freq_staples',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'weekly'::character varying"),
               existing_nullable=False)
    op.alter_column('household_preferences', 'preferred_order_time',
               existing_type=postgresql.TIME(),
               server_default=sa.text("'10:00:00'::time without time zone"),
               existing_nullable=False)
    op.alter_column('household_preferences', 'preferred_order_day',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'sunday'::character varying"),
               existing_nullable=False)
    op.alter_column('household_members', 'health_flags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Bengaluru'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
