from typing import Protocol, runtime_checkable


@runtime_checkable
class LLMProvider(Protocol):
    async def complete(self, system: str, user: str, max_tokens: int = 1024) -> str: ...


@runtime_checkable
class WhatsAppProvider(Protocol):
    async def send_otp(self, phone: str, otp: str) -> None: ...
    async def send_basket_preview(self, phone: str, summary: str, total: float, budget: float) -> None: ...
    async def send_order_receipt(self, phone: str, item_count: int, total: float, area: str, eta: str, order_id: str) -> None: ...
    async def send_reauth_48hr(self, phone: str, expiry_label: str, reauth_url: str) -> None: ...
    async def send_reauth_24hr(self, phone: str, expiry_label: str, reauth_url: str) -> None: ...
    async def send_session_expired(self, phone: str, reauth_url: str) -> None: ...
    async def send_text(self, phone: str, text: str, buttons: list[str] | None = None) -> None: ...


@runtime_checkable
class MCPProvider(Protocol):
    async def get_addresses(self) -> list[dict]: ...
    async def search_products(self, query: str, address_id: str, limit: int = 10) -> list[dict]: ...
    async def your_go_to_items(self, address_id: str) -> list[dict]: ...
    async def get_cart(self) -> dict: ...
    async def update_cart(self, items: list[dict]) -> dict: ...
    async def clear_cart(self) -> None: ...
    async def checkout(self, address_id: str, delivery_slot: str | None = None) -> dict: ...
    async def get_orders(self, limit: int = 20) -> list[dict]: ...
    async def get_order_details(self, order_id: str) -> dict: ...
    async def track_order(self, order_id: str) -> dict: ...
    async def report_error(self, error_type: str, details: str) -> None: ...


@runtime_checkable
class OTPProvider(Protocol):
    async def send(self, household_id: str, phone: str, otp: str) -> None: ...
    async def store(self, household_id: str, phone: str, otp: str, ttl_seconds: int) -> None: ...
    async def get(self, household_id: str, phone: str) -> str | None: ...
    async def delete(self, household_id: str, phone: str) -> None: ...
    async def increment_attempts(self, household_id: str, phone: str) -> int: ...
